sudo: required
services:
  - docker

before_install:
  - docker build -t amarchino/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amarchino/docker-react npm run test -- --coverage